version: '3.8'
services:
  neural_signal_bot:
    container_name: neural_signal_bot
    build: .
    restart: always
    environment:
      - RUNFILE=neural_signal_bot.py
    volumes:
      - ./data:/telegram-bots/data